remote_theme: JetBrains/oss-site-jekyll-theme

# Uncomment for local Docker preview
# theme: jetbrains-oss-jekyll-theme

plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
